// constants/phonemeCatalog.js
// Ported from frontendmain/src/student/platform/LanguagePro/phonetics/phonemeCatalog.js
//
// GENERATED by evaluating the web module and re-serialising it — not retyped, and not regex-parsed.
// This is fixed linguistic content: the General American phoneme set with its how-to text, example
// words, minimal pairs, and the IPA chart coordinates that lay the Sound Studio chart out
// (`manner`/`place` for consonants, `gridPos` for vowels).
//
// A coordinate the chart does not recognise SILENTLY DROPS that sound from the page, which is why
// the web ships a Jest test for it. We cannot run that test here, so the extractor asserts the same
// invariants — unique URL-safe ids, chart coordinates present, every `shape` resolving against
// MOUTH_SHAPES, every minimal pair pointing at a real id — and refuses to emit otherwise.
//
// `id` is a stable ASCII slug, safe in a route param (?sound=eh). Never key anything off raw IPA.

export const PHONEME_CATALOG = [
  {
    "id": "p",
    "ipa": "p",
    "type": "consonant",
    "voiced": false,
    "manner": "stop",
    "place": "lips",
    "label": "'p' as in pen",
    "howTo": "Press both lips together, then release with a small puff of air. No voice.",
    "examples": [
      {
        "word": "pen",
        "ipa": "pɛn"
      },
      {
        "word": "happy",
        "ipa": "hæpi"
      },
      {
        "word": "cup",
        "ipa": "kʌp"
      }
    ],
    "minimalPair": {
      "otherId": "b",
      "note": "pat vs. bat"
    },
    "shape": "closed",
    "release": "bilabialRelease"
  },
  {
    "id": "b",
    "ipa": "b",
    "type": "consonant",
    "voiced": true,
    "manner": "stop",
    "place": "lips",
    "label": "'b' as in bed",
    "howTo": "Press both lips together, then release. Your voice is on — feel your throat buzz.",
    "examples": [
      {
        "word": "bed",
        "ipa": "bɛd"
      },
      {
        "word": "rabbit",
        "ipa": "ɹæbɪt"
      },
      {
        "word": "job",
        "ipa": "dʒɑb"
      }
    ],
    "minimalPair": {
      "otherId": "p",
      "note": "bat vs. pat"
    },
    "shape": "closed",
    "release": "bilabialRelease"
  },
  {
    "id": "t",
    "ipa": "t",
    "type": "consonant",
    "voiced": false,
    "manner": "stop",
    "place": "ridge",
    "label": "'t' as in top",
    "howTo": "Touch the tip of your tongue to the ridge behind your top teeth, then release. No voice.",
    "examples": [
      {
        "word": "top",
        "ipa": "tɑp"
      },
      {
        "word": "water",
        "ipa": "wɔtɚ"
      },
      {
        "word": "cat",
        "ipa": "kæt"
      }
    ],
    "minimalPair": {
      "otherId": "d",
      "note": "ten vs. den"
    },
    "shape": "alveolarClosed",
    "release": "alveolarRelease"
  },
  {
    "id": "d",
    "ipa": "d",
    "type": "consonant",
    "voiced": true,
    "manner": "stop",
    "place": "ridge",
    "label": "'d' as in dog",
    "howTo": "Tongue tip on the ridge behind your top teeth, then release with voice on.",
    "examples": [
      {
        "word": "dog",
        "ipa": "dɔg"
      },
      {
        "word": "ladder",
        "ipa": "lædɚ"
      },
      {
        "word": "red",
        "ipa": "ɹɛd"
      }
    ],
    "minimalPair": {
      "otherId": "t",
      "note": "den vs. ten"
    },
    "shape": "alveolarClosed",
    "release": "alveolarRelease"
  },
  {
    "id": "k",
    "ipa": "k",
    "type": "consonant",
    "voiced": false,
    "manner": "stop",
    "place": "back",
    "label": "'k' as in cat",
    "howTo": "The back of your tongue touches the roof of your mouth at the back, then releases. No voice.",
    "examples": [
      {
        "word": "cat",
        "ipa": "kæt"
      },
      {
        "word": "school",
        "ipa": "skul"
      },
      {
        "word": "back",
        "ipa": "bæk"
      }
    ],
    "minimalPair": {
      "otherId": "g",
      "note": "coat vs. goat"
    },
    "shape": "velarClosed",
    "release": "velarRelease"
  },
  {
    "id": "g",
    "ipa": "g",
    "type": "consonant",
    "voiced": true,
    "manner": "stop",
    "place": "back",
    "label": "'g' as in go",
    "howTo": "Back of the tongue against the back of the roof of your mouth, release with voice on.",
    "examples": [
      {
        "word": "go",
        "ipa": "goʊ"
      },
      {
        "word": "bigger",
        "ipa": "bɪgɚ"
      },
      {
        "word": "bag",
        "ipa": "bæg"
      }
    ],
    "minimalPair": {
      "otherId": "k",
      "note": "goat vs. coat"
    },
    "shape": "velarClosed",
    "release": "velarRelease"
  },
  {
    "id": "m",
    "ipa": "m",
    "type": "consonant",
    "voiced": true,
    "manner": "nasal",
    "place": "lips",
    "label": "'m' as in man",
    "howTo": "Close your lips and hum — the air flows through your nose.",
    "examples": [
      {
        "word": "man",
        "ipa": "mæn"
      },
      {
        "word": "summer",
        "ipa": "sʌmɚ"
      },
      {
        "word": "time",
        "ipa": "taɪm"
      }
    ],
    "minimalPair": {
      "otherId": "n",
      "note": "map vs. nap"
    },
    "shape": "closed"
  },
  {
    "id": "n",
    "ipa": "n",
    "type": "consonant",
    "voiced": true,
    "manner": "nasal",
    "place": "ridge",
    "label": "'n' as in no",
    "howTo": "Tongue tip on the ridge behind your top teeth; hum through your nose.",
    "examples": [
      {
        "word": "no",
        "ipa": "noʊ"
      },
      {
        "word": "funny",
        "ipa": "fʌni"
      },
      {
        "word": "sun",
        "ipa": "sʌn"
      }
    ],
    "minimalPair": {
      "otherId": "m",
      "note": "nap vs. map"
    },
    "shape": "alveolarClosed"
  },
  {
    "id": "ng",
    "ipa": "ŋ",
    "type": "consonant",
    "voiced": true,
    "manner": "nasal",
    "place": "back",
    "label": "'ng' as in sing",
    "howTo": "Back of the tongue up against the roof of your mouth; hum through your nose. Don't add a 'g' sound after it.",
    "examples": [
      {
        "word": "sing",
        "ipa": "sɪŋ"
      },
      {
        "word": "thinking",
        "ipa": "θɪŋkɪŋ"
      },
      {
        "word": "long",
        "ipa": "lɔŋ"
      }
    ],
    "minimalPair": {
      "otherId": "n",
      "note": "sing vs. sin"
    },
    "shape": "velarClosed"
  },
  {
    "id": "f",
    "ipa": "f",
    "type": "consonant",
    "voiced": false,
    "manner": "fricative",
    "place": "teeth",
    "label": "'f' as in fish",
    "howTo": "Touch your top teeth to your bottom lip and blow air through. No voice.",
    "examples": [
      {
        "word": "fish",
        "ipa": "fɪʃ"
      },
      {
        "word": "coffee",
        "ipa": "kɔfi"
      },
      {
        "word": "leaf",
        "ipa": "lif"
      }
    ],
    "minimalPair": {
      "otherId": "v",
      "note": "fan vs. van"
    },
    "shape": "teethOnLip"
  },
  {
    "id": "v",
    "ipa": "v",
    "type": "consonant",
    "voiced": true,
    "manner": "fricative",
    "place": "teeth",
    "label": "'v' as in van",
    "howTo": "Top teeth on your bottom lip, blow air through with your voice on — feel the buzz.",
    "examples": [
      {
        "word": "van",
        "ipa": "væn"
      },
      {
        "word": "seven",
        "ipa": "sɛvən"
      },
      {
        "word": "give",
        "ipa": "gɪv"
      }
    ],
    "minimalPair": {
      "otherId": "f",
      "note": "van vs. fan"
    },
    "shape": "teethOnLip"
  },
  {
    "id": "th",
    "ipa": "θ",
    "type": "consonant",
    "voiced": false,
    "manner": "fricative",
    "place": "teeth",
    "label": "'th' as in think",
    "howTo": "Put the tip of your tongue lightly between your teeth and blow air. No voice.",
    "examples": [
      {
        "word": "think",
        "ipa": "θɪŋk"
      },
      {
        "word": "birthday",
        "ipa": "bɜθdeɪ"
      },
      {
        "word": "math",
        "ipa": "mæθ"
      }
    ],
    "minimalPair": {
      "otherId": "s",
      "note": "think vs. sink"
    },
    "shape": "tongueBetweenTeeth"
  },
  {
    "id": "dh",
    "ipa": "ð",
    "type": "consonant",
    "voiced": true,
    "manner": "fricative",
    "place": "teeth",
    "label": "'th' as in this",
    "howTo": "Tongue tip between your teeth, blow air with your voice on — a soft buzz.",
    "examples": [
      {
        "word": "this",
        "ipa": "ðɪs"
      },
      {
        "word": "mother",
        "ipa": "mʌðɚ"
      },
      {
        "word": "breathe",
        "ipa": "bɹið"
      }
    ],
    "minimalPair": {
      "otherId": "th",
      "note": "this vs. think (voice on/off)"
    },
    "shape": "tongueBetweenTeeth"
  },
  {
    "id": "s",
    "ipa": "s",
    "type": "consonant",
    "voiced": false,
    "manner": "fricative",
    "place": "ridge",
    "label": "'s' as in sun",
    "howTo": "Teeth almost closed, tongue close to the ridge, push a thin hissing stream of air. No voice.",
    "examples": [
      {
        "word": "sun",
        "ipa": "sʌn"
      },
      {
        "word": "lesson",
        "ipa": "lɛsən"
      },
      {
        "word": "bus",
        "ipa": "bʌs"
      }
    ],
    "minimalPair": {
      "otherId": "z",
      "note": "sip vs. zip"
    },
    "shape": "sibilant"
  },
  {
    "id": "z",
    "ipa": "z",
    "type": "consonant",
    "voiced": true,
    "manner": "fricative",
    "place": "ridge",
    "label": "'z' as in zoo",
    "howTo": "Same as 's' but with your voice on — a buzzing bee sound.",
    "examples": [
      {
        "word": "zoo",
        "ipa": "zu"
      },
      {
        "word": "music",
        "ipa": "mjuzɪk"
      },
      {
        "word": "eyes",
        "ipa": "aɪz"
      }
    ],
    "minimalPair": {
      "otherId": "s",
      "note": "zip vs. sip"
    },
    "shape": "sibilant"
  },
  {
    "id": "sh",
    "ipa": "ʃ",
    "type": "consonant",
    "voiced": false,
    "manner": "fricative",
    "place": "ridge",
    "label": "'sh' as in ship",
    "howTo": "Round your lips slightly, pull your tongue a little back, and push air — like asking for quiet: shhh.",
    "examples": [
      {
        "word": "ship",
        "ipa": "ʃɪp"
      },
      {
        "word": "station",
        "ipa": "steɪʃən"
      },
      {
        "word": "fish",
        "ipa": "fɪʃ"
      }
    ],
    "minimalPair": {
      "otherId": "s",
      "note": "ship vs. sip"
    },
    "shape": "roundedNarrow"
  },
  {
    "id": "zh",
    "ipa": "ʒ",
    "type": "consonant",
    "voiced": true,
    "manner": "fricative",
    "place": "ridge",
    "label": "'s' as in vision",
    "howTo": "Same as 'sh' but with your voice on — a soft buzzing shhh.",
    "examples": [
      {
        "word": "vision",
        "ipa": "vɪʒən"
      },
      {
        "word": "usually",
        "ipa": "juʒuəli"
      },
      {
        "word": "measure",
        "ipa": "mɛʒɚ"
      }
    ],
    "minimalPair": {
      "otherId": "sh",
      "note": "vision vs. mission (voice on/off)"
    },
    "shape": "roundedNarrow"
  },
  {
    "id": "h",
    "ipa": "h",
    "type": "consonant",
    "voiced": false,
    "manner": "fricative",
    "place": "back",
    "label": "'h' as in hat",
    "howTo": "Open your mouth for the next vowel and breathe out gently, like fogging a mirror.",
    "examples": [
      {
        "word": "hat",
        "ipa": "hæt"
      },
      {
        "word": "behind",
        "ipa": "bɪhaɪnd"
      },
      {
        "word": "who",
        "ipa": "hu"
      }
    ],
    "minimalPair": null,
    "shape": "breathOpen"
  },
  {
    "id": "ch",
    "ipa": "tʃ",
    "type": "consonant",
    "voiced": false,
    "manner": "affricate",
    "place": "ridge",
    "label": "'ch' as in chair",
    "howTo": "Start like 't' with the tongue on the ridge, release into 'sh'. One quick sound: ch.",
    "examples": [
      {
        "word": "chair",
        "ipa": "tʃɛɹ"
      },
      {
        "word": "teacher",
        "ipa": "titʃɚ"
      },
      {
        "word": "watch",
        "ipa": "wɑtʃ"
      }
    ],
    "minimalPair": {
      "otherId": "sh",
      "note": "chip vs. ship"
    },
    "closure": "alveolarClosed",
    "shape": "roundedNarrow"
  },
  {
    "id": "j",
    "ipa": "dʒ",
    "type": "consonant",
    "voiced": true,
    "manner": "affricate",
    "place": "ridge",
    "label": "'j' as in jump",
    "howTo": "Start like 'd', release into the buzzing 'zh'. Voice on the whole time.",
    "examples": [
      {
        "word": "jump",
        "ipa": "dʒʌmp"
      },
      {
        "word": "subject",
        "ipa": "sʌbdʒɛkt"
      },
      {
        "word": "page",
        "ipa": "peɪdʒ"
      }
    ],
    "minimalPair": {
      "otherId": "ch",
      "note": "jeep vs. cheap"
    },
    "closure": "alveolarClosed",
    "shape": "roundedNarrow"
  },
  {
    "id": "l",
    "ipa": "l",
    "type": "consonant",
    "voiced": true,
    "manner": "approximant",
    "place": "ridge",
    "label": "'l' as in light",
    "howTo": "Tongue tip on the ridge behind your top teeth; let the sound flow around the sides of your tongue.",
    "examples": [
      {
        "word": "light",
        "ipa": "laɪt"
      },
      {
        "word": "yellow",
        "ipa": "jɛloʊ"
      },
      {
        "word": "ball",
        "ipa": "bɔl"
      }
    ],
    "minimalPair": {
      "otherId": "r",
      "note": "light vs. right"
    },
    "shape": "alveolarClosed"
  },
  {
    "id": "r",
    "ipa": "ɹ",
    "type": "consonant",
    "voiced": true,
    "manner": "approximant",
    "place": "ridge",
    "label": "'r' as in red",
    "howTo": "Curl your tongue tip up and back — it touches nothing. Round your lips slightly.",
    "examples": [
      {
        "word": "red",
        "ipa": "ɹɛd"
      },
      {
        "word": "sorry",
        "ipa": "sɑɹi"
      },
      {
        "word": "car",
        "ipa": "kɑɹ"
      }
    ],
    "minimalPair": {
      "otherId": "l",
      "note": "right vs. light"
    },
    "shape": "roundedNarrow"
  },
  {
    "id": "w",
    "ipa": "w",
    "type": "consonant",
    "voiced": true,
    "manner": "approximant",
    "place": "lips",
    "label": "'w' as in wet",
    "howTo": "Round your lips into a tight small circle, then glide open into the next vowel.",
    "examples": [
      {
        "word": "wet",
        "ipa": "wɛt"
      },
      {
        "word": "away",
        "ipa": "əweɪ"
      },
      {
        "word": "quick",
        "ipa": "kwɪk"
      }
    ],
    "minimalPair": {
      "otherId": "v",
      "note": "wet vs. vet"
    },
    "shape": "rounded"
  },
  {
    "id": "y",
    "ipa": "j",
    "type": "consonant",
    "voiced": true,
    "manner": "approximant",
    "place": "back",
    "label": "'y' as in yes",
    "howTo": "Start with your tongue high like 'ee', then glide into the next vowel.",
    "examples": [
      {
        "word": "yes",
        "ipa": "jɛs"
      },
      {
        "word": "million",
        "ipa": "mɪljən"
      },
      {
        "word": "you",
        "ipa": "ju"
      }
    ],
    "minimalPair": {
      "otherId": "j",
      "note": "yet vs. jet"
    },
    "shape": "spread"
  },
  {
    "id": "iy",
    "ipa": "i",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "high",
      "col": "front"
    },
    "label": "'ee' as in see",
    "howTo": "Smile — spread your lips wide, tongue high at the front. A long sound: eee.",
    "examples": [
      {
        "word": "see",
        "ipa": "si"
      },
      {
        "word": "people",
        "ipa": "pipəl"
      },
      {
        "word": "key",
        "ipa": "ki"
      }
    ],
    "minimalPair": {
      "otherId": "ih",
      "note": "sheep vs. ship"
    },
    "shape": "spread"
  },
  {
    "id": "ih",
    "ipa": "ɪ",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "high",
      "col": "front"
    },
    "label": "'i' as in sit",
    "howTo": "Like 'ee' but shorter and more relaxed — lips less spread.",
    "examples": [
      {
        "word": "sit",
        "ipa": "sɪt"
      },
      {
        "word": "busy",
        "ipa": "bɪzi"
      },
      {
        "word": "gym",
        "ipa": "dʒɪm"
      }
    ],
    "minimalPair": {
      "otherId": "iy",
      "note": "ship vs. sheep"
    },
    "shape": "spreadRelaxed"
  },
  {
    "id": "eh",
    "ipa": "ɛ",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "mid",
      "col": "front"
    },
    "label": "'e' as in bed",
    "howTo": "Open your mouth a little more than 'i'; tongue mid-high at the front, lips relaxed.",
    "examples": [
      {
        "word": "bed",
        "ipa": "bɛd"
      },
      {
        "word": "head",
        "ipa": "hɛd"
      },
      {
        "word": "said",
        "ipa": "sɛd"
      }
    ],
    "minimalPair": {
      "otherId": "ae",
      "note": "bed vs. bad"
    },
    "shape": "midFront"
  },
  {
    "id": "ae",
    "ipa": "æ",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "low",
      "col": "front"
    },
    "label": "'a' as in cat",
    "howTo": "Open your mouth wide, tongue low and at the front — a bright open sound.",
    "examples": [
      {
        "word": "cat",
        "ipa": "kæt"
      },
      {
        "word": "hand",
        "ipa": "hænd"
      },
      {
        "word": "apple",
        "ipa": "æpəl"
      }
    ],
    "minimalPair": {
      "otherId": "eh",
      "note": "bad vs. bed"
    },
    "shape": "wideSpread"
  },
  {
    "id": "ah",
    "ipa": "ɑ",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "low",
      "col": "back"
    },
    "label": "'o' as in hot",
    "howTo": "Open wide like at the doctor's — aaah. Tongue low and back.",
    "examples": [
      {
        "word": "hot",
        "ipa": "hɑt"
      },
      {
        "word": "father",
        "ipa": "fɑðɚ"
      },
      {
        "word": "stop",
        "ipa": "stɑp"
      }
    ],
    "minimalPair": {
      "otherId": "uh",
      "note": "cop vs. cup"
    },
    "shape": "wideOpen"
  },
  {
    "id": "aw",
    "ipa": "ɔ",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "mid",
      "col": "back"
    },
    "label": "'aw' as in law",
    "howTo": "Open your mouth, round your lips a little — aww.",
    "examples": [
      {
        "word": "law",
        "ipa": "lɔ"
      },
      {
        "word": "call",
        "ipa": "kɔl"
      },
      {
        "word": "daughter",
        "ipa": "dɔtɚ"
      }
    ],
    "minimalPair": {
      "otherId": "ah",
      "note": "caught vs. cot"
    },
    "shape": "roundedOpen"
  },
  {
    "id": "uh",
    "ipa": "ʌ",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "mid",
      "col": "central"
    },
    "label": "'u' as in cup",
    "howTo": "Mouth slightly open, tongue relaxed in the middle — a short 'uh'.",
    "examples": [
      {
        "word": "cup",
        "ipa": "kʌp"
      },
      {
        "word": "mother",
        "ipa": "mʌðɚ"
      },
      {
        "word": "done",
        "ipa": "dʌn"
      }
    ],
    "minimalPair": {
      "otherId": "ah",
      "note": "cup vs. cop"
    },
    "shape": "midNeutral"
  },
  {
    "id": "schwa",
    "ipa": "ə",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "mid",
      "col": "central"
    },
    "label": "'a' as in about",
    "howTo": "The laziest sound in English — mouth barely open, everything relaxed: uh. Only in unstressed syllables.",
    "examples": [
      {
        "word": "about",
        "ipa": "əbaʊt"
      },
      {
        "word": "banana",
        "ipa": "bənænə"
      },
      {
        "word": "pencil",
        "ipa": "pɛnsəl"
      }
    ],
    "minimalPair": null,
    "shape": "slightOpen"
  },
  {
    "id": "er",
    "ipa": "ɜ",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "mid",
      "col": "central"
    },
    "label": "'er' as in bird",
    "howTo": "Mouth slightly open, curl your tongue up a little, lips slightly rounded — errr.",
    "examples": [
      {
        "word": "bird",
        "ipa": "bɜd"
      },
      {
        "word": "learn",
        "ipa": "lɜn"
      },
      {
        "word": "word",
        "ipa": "wɜd"
      }
    ],
    "minimalPair": null,
    "shape": "roundedNarrow"
  },
  {
    "id": "uu",
    "ipa": "ʊ",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "high",
      "col": "back"
    },
    "label": "'oo' as in book",
    "howTo": "Round your lips a little, tongue high at the back — a short 'oo'.",
    "examples": [
      {
        "word": "book",
        "ipa": "bʊk"
      },
      {
        "word": "good",
        "ipa": "gʊd"
      },
      {
        "word": "push",
        "ipa": "pʊʃ"
      }
    ],
    "minimalPair": {
      "otherId": "uw",
      "note": "full vs. fool"
    },
    "shape": "roundedRelaxed"
  },
  {
    "id": "uw",
    "ipa": "u",
    "type": "vowel",
    "voiced": true,
    "gridPos": {
      "row": "high",
      "col": "back"
    },
    "label": "'oo' as in moon",
    "howTo": "Round your lips into a small tight circle, tongue high at the back — a long 'ooo'.",
    "examples": [
      {
        "word": "moon",
        "ipa": "mun"
      },
      {
        "word": "blue",
        "ipa": "blu"
      },
      {
        "word": "school",
        "ipa": "skul"
      }
    ],
    "minimalPair": {
      "otherId": "uu",
      "note": "fool vs. full"
    },
    "shape": "rounded"
  },
  {
    "id": "ey",
    "ipa": "eɪ",
    "type": "diphthong",
    "voiced": true,
    "label": "'ay' as in day",
    "howTo": "Start with 'e', glide up to 'ee' — one smooth movement: ay.",
    "examples": [
      {
        "word": "day",
        "ipa": "deɪ"
      },
      {
        "word": "make",
        "ipa": "meɪk"
      },
      {
        "word": "rain",
        "ipa": "ɹeɪn"
      }
    ],
    "minimalPair": {
      "otherId": "eh",
      "note": "pain vs. pen"
    },
    "shape": [
      "midFront",
      "spread"
    ]
  },
  {
    "id": "ay",
    "ipa": "aɪ",
    "type": "diphthong",
    "voiced": true,
    "label": "'i' as in my",
    "howTo": "Start wide open with 'ah', glide up to 'ee': eye.",
    "examples": [
      {
        "word": "my",
        "ipa": "maɪ"
      },
      {
        "word": "time",
        "ipa": "taɪm"
      },
      {
        "word": "buy",
        "ipa": "baɪ"
      }
    ],
    "minimalPair": {
      "otherId": "ey",
      "note": "my vs. may"
    },
    "shape": [
      "wideOpen",
      "spread"
    ]
  },
  {
    "id": "oy",
    "ipa": "ɔɪ",
    "type": "diphthong",
    "voiced": true,
    "label": "'oy' as in boy",
    "howTo": "Start with rounded 'aw', glide to 'ee': oy.",
    "examples": [
      {
        "word": "boy",
        "ipa": "bɔɪ"
      },
      {
        "word": "voice",
        "ipa": "vɔɪs"
      },
      {
        "word": "enjoy",
        "ipa": "ɛndʒɔɪ"
      }
    ],
    "minimalPair": null,
    "shape": [
      "roundedOpen",
      "spread"
    ]
  },
  {
    "id": "aw2",
    "ipa": "aʊ",
    "type": "diphthong",
    "voiced": true,
    "label": "'ow' as in now",
    "howTo": "Start wide open with 'ah', glide to rounded 'oo': ow.",
    "examples": [
      {
        "word": "now",
        "ipa": "naʊ"
      },
      {
        "word": "house",
        "ipa": "haʊs"
      },
      {
        "word": "down",
        "ipa": "daʊn"
      }
    ],
    "minimalPair": {
      "otherId": "ow",
      "note": "now vs. no"
    },
    "shape": [
      "wideOpen",
      "rounded"
    ]
  },
  {
    "id": "ow",
    "ipa": "oʊ",
    "type": "diphthong",
    "voiced": true,
    "label": "'o' as in go",
    "howTo": "Start with a relaxed 'o', glide to a tighter rounded 'oo': oh.",
    "examples": [
      {
        "word": "go",
        "ipa": "goʊ"
      },
      {
        "word": "home",
        "ipa": "hoʊm"
      },
      {
        "word": "yellow",
        "ipa": "jɛloʊ"
      }
    ],
    "minimalPair": {
      "otherId": "aw",
      "note": "boat vs. bought"
    },
    "shape": [
      "roundedRelaxed",
      "rounded"
    ]
  }
];

/** Lookup by the URL-safe slug. */
export function findById(id) {
  return PHONEME_CATALOG.find((p) => p.id === id) || null;
}

/** The three chart sections, in the web's order. */
export const CONSONANTS = PHONEME_CATALOG.filter((p) => p.type === 'consonant');
export const VOWELS = PHONEME_CATALOG.filter((p) => p.type === 'vowel');
export const DIPHTHONGS = PHONEME_CATALOG.filter((p) => p.type === 'diphthong');
