import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SPACING, TYPE } from '../../constants/theme';
import { Card, ScreenScaffold } from '../ui';
import { usePalette } from '../ui/PaletteContext';
import { makeStyles } from '../../utils/makeStyles';
import PARTNER_SCHOOL_PLANS from '../../constants/partnerSchoolPlans';

/**
 * Plans for Schools — the sales sheet a partner shows a school's decision-makers.
 *
 * Ports frontendmain/src/Partner/platform/PartnerSchoolPlans.js. This tab calls no API at all;
 * the web holds the same four plans as an inline literal. Here they live in
 * constants/partnerSchoolPlans.js, generated by EVALUATING the web literal rather than retyping
 * it — 36 feature lines and a revenue table is exactly the content a hand-copy corrupts silently.
 *
 * Accordion rather than four long cards: on a phone the web's side-by-side comparison becomes
 * ~10 screens of vertical scroll, and a partner presenting this needs to jump to one plan.
 *
 * The web's "download the PDF" button is deliberately absent — it links to a file on
 * shreyartha.com, i.e. a WebView hand-off, and everything in that PDF is already on this screen.
 */

export default function PartnerSchoolPlansScreen({ homeRoute = '/partner' }) {
  const styles = useStyles();
  const palette = usePalette();
  const [openId, setOpenId] = useState(PARTNER_SCHOOL_PLANS[0]?.id ?? null);

  return (
    <ScreenScaffold title="Plans for Schools" fallbackRoute={homeRoute}>
      <Text style={styles.intro}>
        Shreyartha.ai school partnership plans. Share these with school administrators and
        decision-makers.
      </Text>

      {PARTNER_SCHOOL_PLANS.map((plan) => {
        const open = openId === plan.id;
        return (
          <Card key={plan.id} style={styles.card}>
            <Pressable
              onPress={() => setOpenId(open ? null : plan.id)}
              style={({ pressed }) => [styles.head, pressed && styles.pressed]}
              accessibilityRole="button"
              accessibilityState={{ expanded: open }}
              accessibilityLabel={`${plan.name}, ${plan.price} ${plan.priceLabel}`}
            >
              {/* The accent colour is part of the plan data, so it is applied inline rather than
                  through a palette token — these four hues identify the tiers on the sales sheet
                  and are not part of the portal's theme. */}
              <View style={[styles.accent, { backgroundColor: plan.accent }]} />
              <View style={styles.headText}>
                <Text style={styles.name}>{plan.name}</Text>
                <Text style={styles.subtitle}>{plan.subtitle}</Text>
                <View style={styles.priceRow}>
                  <Text style={[styles.price, { color: plan.accent }]}>{plan.price}</Text>
                  <Text style={styles.priceLabel}>{plan.priceLabel}</Text>
                </View>
              </View>
              <Ionicons
                name={open ? 'chevron-up' : 'chevron-down'}
                size={18}
                color={palette.primaryDark}
              />
            </Pressable>

            {open ? (
              <View style={styles.body}>
                {plan.sections.map((section) => (
                  <View key={section.title} style={styles.section}>
                    <Text style={styles.sectionTitle}>{section.title}</Text>
                    {section.items.map((item) => (
                      <View key={item.text} style={styles.item}>
                        <Ionicons
                          name={item.included ? 'checkmark-circle' : 'close-circle'}
                          size={16}
                          color={item.included ? plan.accent : styles.excludedIcon.color}
                        />
                        <Text
                          style={[
                            styles.itemText,
                            item.bold && styles.itemBold,
                            !item.included && styles.itemExcluded,
                          ]}
                        >
                          {item.text}
                        </Text>
                      </View>
                    ))}
                  </View>
                ))}

                {plan.revenueTable ? (
                  <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Revenue share</Text>
                    {plan.revenueTable.map((row) => (
                      <View key={row.stakeholder} style={styles.revRow}>
                        <Text style={styles.revWho}>{row.stakeholder}</Text>
                        <Text style={styles.revShare}>{row.share}</Text>
                      </View>
                    ))}
                  </View>
                ) : null}
              </View>
            ) : null}
          </Card>
        );
      })}
    </ScreenScaffold>
  );
}

const useStyles = makeStyles((p) => ({
  intro: {
    fontSize: TYPE.label,
    color: p.primaryDark,
    opacity: 0.85,
    marginBottom: SPACING.md,
    lineHeight: 18,
  },
  card: { padding: 0, overflow: 'hidden' },
  head: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm, padding: SPACING.md },
  accent: { width: 4, alignSelf: 'stretch', borderRadius: 2 },
  headText: { flex: 1 },
  name: { fontSize: TYPE.title, fontWeight: '700', color: p.primaryDark },
  subtitle: { fontSize: TYPE.caption, color: p.primaryDark, opacity: 0.7, marginTop: 2 },
  priceRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6, marginTop: 6 },
  price: { fontSize: TYPE.headline, fontWeight: '800' },
  priceLabel: { fontSize: TYPE.caption, color: p.primaryDark, opacity: 0.7, flexShrink: 1 },

  body: { paddingHorizontal: SPACING.md, paddingBottom: SPACING.md },
  section: { marginTop: SPACING.sm },
  sectionTitle: {
    fontSize: TYPE.caption,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: p.primaryDark,
    opacity: 0.65,
    marginBottom: 6,
  },
  item: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 6 },
  itemText: { flex: 1, fontSize: TYPE.label, color: p.primaryDark, lineHeight: 18 },
  itemBold: { fontWeight: '700' },
  itemExcluded: { opacity: 0.5, textDecorationLine: 'line-through' },
  // Referenced as a colour, not applied as a style — see the Ionicons call above.
  excludedIcon: { color: p.cardBorder },

  revRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: SPACING.sm,
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: p.cardBorder,
  },
  revWho: { flex: 1, fontSize: TYPE.label, fontWeight: '600', color: p.primaryDark },
  revShare: { flex: 1, fontSize: TYPE.caption, color: p.primaryDark, opacity: 0.8, textAlign: 'right' },
  pressed: { opacity: 0.75 },
}));
